### ISSUE TITLE
1.17.1 update?

### ISSUE THREAD

**Issue by TMCThomas** [rexlManu/decompiled-shop-plugin#1]
Hey, I wondered if you might be able to update it to 1.17.1? It seems to be broken again. 

16.11 20:14:10 [Server] ERROR Error occurred while enabling Shop v2.1.0 (Is it up to date?)
16.11 20:14:10 [Server] INFO java.lang.IllegalArgumentException: Trait name shop already registered
16.11 20:14:10 [Server] INFO at net.citizensnpcs.npc.CitizensTraitFactory.registerTrait(CitizensTraitFactory.java:182) ~[Citizens-2.0.28-b2398.jar:?]
16.11 20:14:10 [Server] INFO at conj.Shop.base.Initiate.onEnable(Initiate.java:129) ~[shop-1.0-SNAPSHOT.jar:?]
16.11 20:14:10 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:731) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-377]
16.11 20:14:10 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
16.11 20:14:10 [Server] INFO [Shop] Disabling Shop v2.1.0

**Comment by rexlManu** [comment]
Hey, I could update it to 1.17.1 but I would recommend you, to use a alternative to this plugin. Mainly because i'm not the developer of this plugin the first place.

**Comment by TMCThomas** [comment]
Hi! Thanks for your response! I found someone that already has a 1.17.1 build voor personal use so I'm good! Might switch later but don't really have to time to convert everything to a different plugin hahah.
